# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: .
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - formats: [tar.gz]
    # Make the OS and Arch names compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

aurs:
  - name: dman
    homepage: https://github.com/alexjoedt/dman
    description: A dotfile manager focused on Git overlay model and snapshots
    license: MIT
    maintainers:
      - Alex Joedt <alex at joedt dot com>
    git_url: ssh://aur@aur.archlinux.org/dman.git
    private_key: "{{ .Env.AUR_KEY }}"
    provides:
      - dman
    conflicts:
      - dman
    package: |-
      install -Dm755 dman "${pkgdir}/usr/bin/dman"
      install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
      install -Dm644 README.md "${pkgdir}/usr/share/doc/${pkgname}/README.md"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
